batch_size: 1024
data_fraction: 0.1
exp_setup:
- 0
- pos
- single_weight
file_name_eval: null
hidden_channels:
- 8
- 16
- 64
- 128
- 128
- 64
- 16
- 8
image_size:
- 640
- 480
in_channels: 2
label: default
learning_rate: 0.001
node_loss_weight:
- 1
- 1
out_channels: 13
pck_multiplier: 0.6
save_video: null
task: all
transforms:
- check_x_size
- use_pos_as_input
visualise: false
write_csv: null
