#!/usr/bin/env python3
"""
YARP sidecar for MasterHow/EventPointPose PointNet (DHP19 MeanLabel checkpoint).

Default deployment mode
-----------------------
The input ``data.log`` files are assumed to have been generated by the standard
hpe-core DHP19 preprocessing/export pipeline. Therefore hot-pixel filtering,
background filtering, and the two IR masks have already been applied and are
skipped by default (``--input_preprocessing already_filtered``).

Request Bottle (C++ -> Python)
------------------------------
    bottle[0] : int32 request id
    bottle[1] : float64 inference timestamp (seconds)
    bottle[2] : int32 camera id
    bottle[3] : flat list of events [x, y, packet_timestamp, polarity, ...]

The event coordinates in a preprocessed hpe-core log are local, zero-based,
and already flipped by the DHP19 preprocessing/export path. Before RasEPC they
are converted back to the exact MeanLabel point-cloud representation used by
EventPointPose:

    x_epp = x_log + 1
    y_epp = (sensor_height - 1) - y_log

RasEPC itself then performs the repository's own ``int() - 1`` indexing.

Reply Bottle (Python -> C++)
----------------------------
The reply remains compatible with hpe-core::extractSkeletonFromYARP():
    bottle[0] : float64 inference timestamp
    bottle[1] : list of 39 floats
                  26 coordinates: x0,y0,...,x12,y12
                  13 confidences (1.0 for a valid EventPointPose prediction)
    bottle[2] : string status: OK, WARMUP, NO_UPDATE, ERROR, SHUTDOWN
    bottle[3] : int32 request id
    bottle[4] : diagnostic list
                  accepted_events, fifo_size, rasepc_points, inference_ms
    bottle[5] : optional diagnostic/error message

The FIFO is persistent and contains at most the 7500 most recent accepted
input events. A new PointNet inference is executed only when the current batch
adds at least one event and the FIFO is full.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import os
import signal
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Optional, Sequence, Tuple

# Required by CUDA when deterministic algorithms are requested by the runtime.
# Setting it before importing torch is harmless on CPU and on older PyTorch builds.
os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

try:
    import yarp  # type: ignore
except ImportError:
    yarp = None


SENSOR_WIDTH = 346
SENSOR_HEIGHT = 260
NUM_JOINTS = 13
RASEPC_CHANNELS = 4
FIFO_SIZE = 7500
POINTNET_POINTS = 2048

# EventPointPose native order:
# head, shoulderR, shoulderL, elbowR, elbowL, hipR, hipL,
# handR, handL, kneeR, kneeL, footR, footL
#
# hpe-core order:
# head, shoulderR, shoulderL, elbowR, elbowL, hipL, hipR,
# handR, handL, kneeR, kneeL, footR, footL
HPE_FROM_EPP = np.asarray([0, 1, 2, 3, 4, 6, 5, 7, 8, 9, 10, 11, 12], dtype=np.int64)


class PosePointNet(nn.Module):
    """Exact PointNet architecture from MasterHow/EventPointPose/models/PointNet.py."""

    def __init__(self, args: SimpleNamespace):
        super().__init__()
        self.args = args
        self.sizeH = args.sensor_sizeH
        self.sizeW = args.sensor_sizeW
        self.num_joints = args.num_joints

        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(64)
        self.bn3 = nn.BatchNorm1d(128)
        self.bn4 = nn.BatchNorm1d(256)
        self.bn5 = nn.BatchNorm1d(1024)
        self.bn6 = nn.BatchNorm1d(1024)
        self.bn7 = nn.BatchNorm1d(self.num_joints * 128)

        self.dp1 = nn.Dropout(p=0.1)
        self.dp2 = nn.Dropout(p=0.1)

        self.conv1 = nn.Sequential(
            nn.Conv1d(5, 64, kernel_size=1, bias=False),
            self.bn1,
            nn.LeakyReLU(),
        )
        self.conv2 = nn.Sequential(
            nn.Conv1d(64, 64, kernel_size=1, bias=False),
            self.bn2,
            nn.LeakyReLU(),
        )
        self.conv3 = nn.Sequential(
            nn.Conv1d(64, 128, kernel_size=1, bias=False),
            self.bn3,
            nn.LeakyReLU(),
        )
        self.conv4 = nn.Sequential(
            nn.Conv1d(128, 256, kernel_size=1, bias=False),
            self.bn4,
            nn.LeakyReLU(),
        )
        self.conv5 = nn.Sequential(
            nn.Conv1d(512, 1024, kernel_size=1, bias=False),
            self.bn5,
            nn.LeakyReLU(),
        )

        self.out_conv1 = nn.Sequential(
            nn.Linear(1024 * 2, 1024, bias=False),
            self.bn6,
            nn.LeakyReLU(),
            self.dp1,
        )
        self.out_conv2 = nn.Sequential(
            nn.Linear(1024, self.num_joints * 128, bias=False),
            self.bn7,
            nn.LeakyReLU(),
            self.dp2,
        )

        self.mlp_head_x = nn.Linear(128, self.sizeW)
        self.mlp_head_y = nn.Linear(128, self.sizeH)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        batch_size = x.size(0)
        x1 = self.conv1(x)
        x2 = self.conv2(x1)
        x3 = self.conv3(x2)
        x4 = self.conv4(x3)
        x = torch.cat((x1, x2, x3, x4), dim=1)

        x = self.conv5(x)

        x1 = F.adaptive_max_pool1d(x, 1).view(batch_size, -1)
        x2 = F.adaptive_avg_pool1d(x, 1).view(batch_size, -1)
        x = torch.cat((x1, x2), 1)

        x = self.out_conv1(x)
        x = self.out_conv2(x)

        x = x.view(batch_size, self.num_joints, -1)
        pred_x = self.mlp_head_x(x)
        pred_y = self.mlp_head_y(x)
        return pred_x, pred_y


class RasEventCloud:
    """Line-for-line numerical reproduction of dataset/rasterized.py."""

    def __init__(self, input_size: tuple[int, int, int]):
        if len(input_size) != 3:
            raise ValueError("RasEventCloud input_size must be (channels, height, width)")

        self.channels = input_size[0]
        self.height = input_size[1]
        self.width = input_size[2]

        self.cloud_channel_grid = torch.ones(input_size, dtype=torch.float, requires_grad=False)
        for i in range(self.channels):
            self.cloud_channel_grid[i] *= i

        y_cord = torch.tensor([i for i in range(self.height)])
        x_cord = torch.tensor([i for i in range(self.width)])
        try:
            y, x = torch.meshgrid(y_cord, x_cord, indexing="ij")
        except TypeError:  # PyTorch 1.8 compatibility
            y, x = torch.meshgrid(y_cord, x_cord)
        y = y.unsqueeze(0)
        x = x.unsqueeze(0)
        self.y_grid = y.expand(self.channels, -1, -1)
        self.x_grid = x.expand(self.channels, -1, -1)

    def convert(self, events: np.ndarray) -> torch.Tensor:
        """Return [channel, x, y, t_avg, p_acc, event_count]."""
        if events.ndim != 2 or events.shape[1] < 4:
            raise ValueError(f"RasEPC expects [N,4+] events, received {events.shape}")
        if events.shape[0] == 0:
            return torch.empty((0, 6), dtype=torch.float32)

        # Copy because the original implementation modifies the timestamp column.
        events_t = torch.from_numpy(np.ascontiguousarray(events[:, :4]).copy())
        C, H, W = self.channels, self.height, self.width

        cloud_polar_grid = torch.zeros((C, H, W), dtype=torch.float, requires_grad=False)
        cloud_time_acc_grid = torch.zeros((C, H, W), dtype=torch.float, requires_grad=False)
        cloud_event_count_grid = torch.zeros((C, H, W), dtype=torch.float, requires_grad=False)

        events_t[:, 2] = events_t[:, 2] - events_t[:, 2].min()
        max_time = events_t[:, 2].max()
        if float(max_time.item()) == 0.0:
            raise ValueError("RasEPC received a zero-duration event window")
        events_t[:, 2] = (events_t[:, 2] / max_time) / 1.001
        events_t[:, 2] = events_t[:, 2] * self.channels

        with torch.no_grad():
            t = events_t[:, 2]
            p = 2 * events_t[:, 3] - 1
            t0 = events_t[:, 2].int()
            x = events_t[:, 0].int() - 1
            y = events_t[:, 1].int() - 1

            index = H * W * t0.long() + W * y.long() + x.long()
            cloud_polar_grid.put_(index, p.float(), accumulate=True)
            cloud_time_acc_grid.put_(index, (t - t0).float(), accumulate=True)
            cloud_event_count_grid.put_(
                index, torch.ones_like(x, dtype=torch.float), accumulate=True
            )

            valid_mask = torch.ne(cloud_event_count_grid, 0)
            data_list = [
                self.cloud_channel_grid[valid_mask].reshape(-1, 1),
                self.x_grid[valid_mask].reshape(-1, 1),
                self.y_grid[valid_mask].reshape(-1, 1),
                cloud_time_acc_grid[valid_mask].reshape(-1, 1),
                cloud_polar_grid[valid_mask].reshape(-1, 1),
                cloud_event_count_grid[valid_mask].reshape(-1, 1),
            ]

            data = torch.cat(data_list, 1)
            data[:, 3] /= data[:, 5]
            data[:, 3] = data[:, 3] / C + data[:, 0] / C
            return data


class EventFIFO:
    """Fixed-capacity FIFO preserving event order without clearing after inference."""

    def __init__(self, capacity: int):
        if capacity <= 0:
            raise ValueError("FIFO capacity must be positive")
        self.capacity = int(capacity)
        self._data = np.empty((self.capacity, 4), dtype=np.float64)
        self._write = 0
        self._count = 0

    def __len__(self) -> int:
        return self._count

    def append(self, events: np.ndarray) -> None:
        if events.size == 0:
            return
        events = np.asarray(events, dtype=np.float64)
        if events.ndim != 2 or events.shape[1] != 4:
            raise ValueError(f"FIFO expects [N,4], received {events.shape}")

        n = events.shape[0]
        if n >= self.capacity:
            self._data[:, :] = events[-self.capacity :, :]
            self._write = 0
            self._count = self.capacity
            return

        first = min(n, self.capacity - self._write)
        self._data[self._write : self._write + first, :] = events[:first, :]
        remaining = n - first
        if remaining:
            self._data[0:remaining, :] = events[first:, :]
        self._write = (self._write + n) % self.capacity
        self._count = min(self.capacity, self._count + n)

    def latest(self) -> np.ndarray:
        if self._count == 0:
            return np.empty((0, 4), dtype=np.float64)
        if self._count < self.capacity:
            return self._data[: self._count, :].copy()
        if self._write == 0:
            return self._data.copy()
        return np.concatenate(
            (self._data[self._write :, :], self._data[: self._write, :]), axis=0
        )


@dataclass
class FilterStats:
    received: int = 0
    accepted: int = 0
    invalid: int = 0
    hot: int = 0
    background: int = 0
    ir: int = 0


class OnlineEventPreprocessor:
    """
    Event preprocessing for two input modes.

    already_filtered (default):
        Input comes from hpe-core DHP19 data.log. All three filters are skipped,
        and coordinates are converted to the EventPointPose MeanLabel format.

    raw:
        Input coordinates are interpreted as raw local zero-based DAVIS346
        coordinates. A precomputed hot-pixel mask, the original online-style
        background filter, and the original two global IR masks are applied.
        This mode is retained for controlled experiments; it is not used for
        the standard hpe-core logs supplied with this task.
    """

    def __init__(
        self,
        input_preprocessing: str,
        background_domain: str,
        hotpixel_path: str,
        width: int,
        height: int,
        dt_us: float,
    ):
        self.input_preprocessing = input_preprocessing
        self.background_domain = background_domain
        self.width = int(width)
        self.height = int(height)
        self.dt_us = float(dt_us)

        self.hot_mask: Optional[np.ndarray] = None
        self.last_times: Optional[np.ndarray] = None

        if self.input_preprocessing == "raw":
            self.hot_mask = self._load_hot_mask(hotpixel_path)
            xdim = self.width * 4 if self.background_domain == "global" else self.width
            # MATLAB indexes the map as lastTimesMap(x, y), with 1-based coordinates.
            self.last_times = np.zeros((xdim + 1, self.height + 1), dtype=np.float64)

    def process(self, events: np.ndarray, camera: int) -> Tuple[np.ndarray, FilterStats]:
        stats = FilterStats(received=int(events.shape[0]))
        if events.size == 0:
            return np.empty((0, 4), dtype=np.float64), stats

        events = np.asarray(events, dtype=np.float64)
        x = events[:, 0].astype(np.int64, copy=False)
        y = events[:, 1].astype(np.int64, copy=False)
        t = events[:, 2].astype(np.float64, copy=False)
        p = events[:, 3].astype(np.int64, copy=False)

        valid = (
            (x >= 0)
            & (x < self.width)
            & (y >= 0)
            & (y < self.height)
            & ((p == 0) | (p == 1))
            & np.isfinite(t)
        )
        stats.invalid = int((~valid).sum())
        x, y, t, p = x[valid], y[valid], t[valid], p[valid]

        if x.size == 0:
            return np.empty((0, 4), dtype=np.float64), stats

        if self.input_preprocessing == "already_filtered":
            # Exact reconstruction of the .npy MeanLabel point-cloud coordinates.
            x_epp = x + 1
            y_epp = (self.height - 1) - y
            result = np.column_stack((x_epp, y_epp, t, p)).astype(np.float64, copy=False)
            stats.accepted = int(result.shape[0])
            return result, stats

        # Optional raw-input path. The original MATLAB transformation is:
        # X = (sx - x_raw) + cam*sx; Y = sy - y_raw.
        x_raw, y_raw = x, y

        if self.hot_mask is not None:
            is_hot = self.hot_mask[y_raw, x_raw]
            stats.hot = int(is_hot.sum())
            keep = ~is_hot
            x_raw, y_raw, t, p = x_raw[keep], y_raw[keep], t[keep], p[keep]

        if x_raw.size == 0:
            return np.empty((0, 4), dtype=np.float64), stats

        x_global = (self.width - x_raw) + camera * self.width
        y_global = self.height - y_raw

        bg_keep = self._background_filter(x_global, y_global, t, camera)
        stats.background = int((~bg_keep).sum())
        x_global, y_global, t, p = (
            x_global[bg_keep],
            y_global[bg_keep],
            t[bg_keep],
            p[bg_keep],
        )

        if x_global.size == 0:
            return np.empty((0, 4), dtype=np.float64), stats

        # Original maskRegionFilter uses strict inequalities.
        mask1 = (
            (x_global > 780)
            & (x_global < 810)
            & (y_global > 115)
            & (y_global < 145)
        )
        mask2 = (
            (x_global > (self.width * 3 + 214))
            & (x_global < (self.width * 3 + 221))
            & (y_global > 136)
            & (y_global < 144)
        )
        is_ir = mask1 | mask2
        stats.ir = int(is_ir.sum())
        keep = ~is_ir
        x_global, y_global, t, p = (
            x_global[keep],
            y_global[keep],
            t[keep],
            p[keep],
        )

        x_epp = x_global - camera * self.width
        y_epp = self.height - y_global
        result = np.column_stack((x_epp, y_epp, t, p)).astype(np.float64, copy=False)
        stats.accepted = int(result.shape[0])
        return result, stats

    def _background_filter(
        self, x_global: np.ndarray, y_global: np.ndarray, t_seconds: np.ndarray, camera: int
    ) -> np.ndarray:
        if self.last_times is None:
            raise RuntimeError("Background filter state is not initialized")

        if self.background_domain == "global":
            xs = x_global
            xdim = self.width * 4
        else:
            xs = x_global - camera * self.width
            xdim = self.width

        ys = y_global
        keep = np.ones(xs.shape[0], dtype=bool)

        # hpe-core logs normally start at t=0. The original MATLAB filter uses
        # large absolute microsecond timestamps and a zero-initialized map, so
        # add a constant offset to preserve the original first-event rejection.
        times_us = t_seconds * 1e6 + self.dt_us + 1.0

        for i in range(xs.shape[0]):
            xi = int(xs[i])
            yi = int(ys[i])
            ts = float(times_us[i])
            delta_t = ts - self.last_times[xi, yi]
            if delta_t > self.dt_us:
                keep[i] = False

            # The repository updates the eight neighbours even when the current
            # event is rejected; it never updates the event's own pixel.
            if not (xi == 1 or xi == xdim or yi == 1 or yi == self.height):
                self.last_times[xi - 1, yi] = ts
                self.last_times[xi + 1, yi] = ts
                self.last_times[xi, yi - 1] = ts
                self.last_times[xi, yi + 1] = ts
                self.last_times[xi - 1, yi - 1] = ts
                self.last_times[xi + 1, yi + 1] = ts
                self.last_times[xi - 1, yi + 1] = ts
                self.last_times[xi + 1, yi - 1] = ts

        return keep

    def _load_hot_mask(self, path_value: str) -> Optional[np.ndarray]:
        if not path_value:
            return None

        path = Path(path_value)
        if path.is_dir():
            candidates = [
                path / "hotpixel_mask.npy",
                path / "hotpixel_pixels.csv",
                path / "hotpixel_mask.png",
            ]
            resolved = next((candidate for candidate in candidates if candidate.exists()), None)
            if resolved is None:
                raise FileNotFoundError(
                    f"No supported hot-pixel mask found in directory: {path_value}"
                )
            path = resolved

        if not path.exists():
            raise FileNotFoundError(f"Hot-pixel mask not found: {path_value}")

        suffix = path.suffix.lower()
        if suffix == ".npy":
            mask = np.asarray(np.load(path, allow_pickle=False), dtype=bool)
            if mask.shape != (self.height, self.width):
                raise ValueError(
                    f"Expected hot-pixel mask {(self.height, self.width)}, got {mask.shape}"
                )
            return mask

        if suffix == ".csv":
            mask = np.zeros((self.height, self.width), dtype=bool)
            with path.open("r", newline="") as stream:
                reader = csv.DictReader(stream)
                if reader.fieldnames is None:
                    return mask
                lower = {name.lower(): name for name in reader.fieldnames}
                if "x" not in lower or "y" not in lower:
                    # An empty file containing only an unrelated header is treated
                    # as an empty mask rather than as a runtime failure.
                    return mask
                for row in reader:
                    if not row:
                        continue
                    xi = int(float(row[lower["x"]]))
                    yi = int(float(row[lower["y"]]))
                    if 0 <= xi < self.width and 0 <= yi < self.height:
                        mask[yi, xi] = True
            return mask

        if suffix == ".png":
            try:
                import cv2  # type: ignore
            except ImportError as exc:
                raise RuntimeError("OpenCV is required to load a PNG hot-pixel mask") from exc
            image = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
            if image is None:
                raise ValueError(f"Could not read hot-pixel image: {path}")
            if image.shape != (self.height, self.width):
                raise ValueError(
                    f"Expected hot-pixel image {(self.height, self.width)}, got {image.shape}"
                )
            return image != 0

        raise ValueError(f"Unsupported hot-pixel format: {path}")


class EventPointPoseEngine:
    def __init__(self, args: argparse.Namespace):
        self.args = args
        self.device = resolve_device(args.device)
        configure_determinism(args.seed)

        model_args = SimpleNamespace(
            sensor_sizeH=args.h,
            sensor_sizeW=args.w,
            num_joints=NUM_JOINTS,
        )
        self.model = PosePointNet(model_args).to(self.device)
        load_checkpoint_strict(self.model, args.model, self.device)
        self.model.eval()

        self.rasepc = RasEventCloud((args.rasepc_channels, args.h, args.w))
        self.rng = np.random.RandomState(args.seed)
        self.fifo = EventFIFO(args.fifo_size)
        self.preprocessor = OnlineEventPreprocessor(
            input_preprocessing=args.input_preprocessing,
            background_domain=args.background_domain,
            hotpixel_path=args.hotpixel_path,
            width=args.w,
            height=args.h,
            dt_us=args.background_dt_us,
        )

        self.dump_dir: Optional[Path] = None
        if args.dump_debug_dir:
            self.dump_dir = Path(args.dump_debug_dir)
            self.dump_dir.mkdir(parents=True, exist_ok=True)
        self.dumped = 0

    def process_request(
        self, request_id: int, camera: int, events: np.ndarray
    ) -> Tuple[str, np.ndarray, np.ndarray, Sequence[float]]:
        processed, filter_stats = self.preprocessor.process(events, camera)
        accepted = int(processed.shape[0])

        if accepted == 0:
            return (
                "NO_UPDATE",
                np.zeros((NUM_JOINTS, 2), dtype=np.float32),
                np.zeros(NUM_JOINTS, dtype=np.float32),
                [0, len(self.fifo), 0, 0.0],
            )

        self.fifo.append(processed)
        if len(self.fifo) < self.args.fifo_size:
            return (
                "WARMUP",
                np.zeros((NUM_JOINTS, 2), dtype=np.float32),
                np.zeros(NUM_JOINTS, dtype=np.float32),
                [accepted, len(self.fifo), 0, 0.0],
            )

        window = self.fifo.latest()
        if window.shape[0] != self.args.fifo_size:
            raise RuntimeError(
                f"Internal FIFO error: expected {self.args.fifo_size}, got {window.shape[0]}"
            )

        # Packet timestamps are repeated for every event in a packet. If the
        # complete FIFO has only one distinct timestamp, use progressive event
        # rank as the explicitly requested fallback.
        if float(np.max(window[:, 2]) - np.min(window[:, 2])) == 0.0:
            window[:, 2] = np.arange(window.shape[0], dtype=np.float64)

        start = time.perf_counter()
        rasepc_full = self.rasepc.convert(window).cpu().numpy()
        rasepc = rasepc_full[:, 1:]  # [x, y, t_avg, p_acc, event_count]
        if rasepc.shape[0] == 0:
            raise RuntimeError("RasEPC produced no points from a non-empty FIFO")

        sampled, sample_indices = random_sample_point_exact(
            rasepc, self.args.num_points, self.rng
        )
        pointnet_input = np.ascontiguousarray(sampled.T[None, :, :], dtype=np.float32)
        tensor = torch.from_numpy(pointnet_input).to(self.device)

        with torch.no_grad():
            pred_x_logits, pred_y_logits = self.model(tensor)
            pred_x = torch.argmax(pred_x_logits, dim=2)[0].cpu().numpy()
            pred_y = torch.argmax(pred_y_logits, dim=2)[0].cpu().numpy()

        native_xy = np.stack((pred_x, pred_y), axis=1).astype(np.float32)
        hpe_xy = native_xy[HPE_FROM_EPP, :]
        conf = np.ones(NUM_JOINTS, dtype=np.float32)
        inference_ms = (time.perf_counter() - start) * 1000.0

        if self.dump_dir is not None and self.dumped < self.args.dump_first_n:
            prefix = self.dump_dir / f"request_{request_id:08d}"
            np.save(str(prefix) + "_request_log.npy", events)
            np.save(
                str(prefix) + "_filter_stats.npy",
                np.asarray(
                    [
                        filter_stats.received,
                        filter_stats.accepted,
                        filter_stats.invalid,
                        filter_stats.hot,
                        filter_stats.background,
                        filter_stats.ir,
                    ],
                    dtype=np.int64,
                ),
            )
            np.save(str(prefix) + "_accepted_batch_epp.npy", processed)
            np.save(str(prefix) + "_fifo_epp.npy", window)
            np.save(str(prefix) + "_rasepc_full.npy", rasepc_full)
            np.save(str(prefix) + "_rasepc_features.npy", rasepc)
            np.save(str(prefix) + "_sample_indices.npy", sample_indices)
            np.save(str(prefix) + "_pointnet_input.npy", pointnet_input)
            np.save(str(prefix) + "_native_prediction.npy", native_xy)
            np.save(str(prefix) + "_hpecore_prediction.npy", hpe_xy)
            self.dumped += 1

        return (
            "OK",
            hpe_xy,
            conf,
            [accepted, len(self.fifo), int(rasepc.shape[0]), inference_ms],
        )


def random_sample_point_exact(
    xyz: np.ndarray, npoint: int, rng: np.random.RandomState
) -> Tuple[np.ndarray, np.ndarray]:
    """Exact sampling policy from dataset/sample.py, using a deterministic RNG."""
    n_points, _ = xyz.shape
    if n_points == 0:
        raise ValueError("Cannot sample an empty RasEPC point cloud")
    index_range = np.arange(n_points)
    if npoint <= n_points:
        selected = np.sort(rng.choice(index_range, size=npoint, replace=False, p=None))
    else:
        selected = np.sort(rng.choice(index_range, size=npoint, replace=True, p=None))
    return xyz[selected, :], selected


def configure_determinism(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    if hasattr(torch.backends, "cudnn"):
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    # PointNet uses deterministic Conv1d/Linear/pooling operations on supported
    # PyTorch/CUDA combinations. Avoid forcing a global mode that can make old
    # PyTorch 1.8 builds reject otherwise valid operations.


def resolve_device(value: str) -> torch.device:
    value = value.strip()
    if not value:
        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    if value.isdigit():
        value = f"cuda:{value}"
    device = torch.device(value)
    if device.type == "cuda" and not torch.cuda.is_available():
        print(
            f"Warning: CUDA device {value} requested but CUDA is unavailable; using CPU.",
            file=sys.stderr,
            flush=True,
        )
        return torch.device("cpu")
    return device


def extract_state_dict(checkpoint: object) -> dict[str, torch.Tensor]:
    if isinstance(checkpoint, dict):
        for key in ("state_dict", "model_state_dict", "model"):
            candidate = checkpoint.get(key)
            if isinstance(candidate, dict):
                checkpoint = candidate
                break
    if not isinstance(checkpoint, dict):
        raise TypeError("Checkpoint does not contain a state_dict")

    state_dict: dict[str, torch.Tensor] = {}
    for key, value in checkpoint.items():
        if not isinstance(value, torch.Tensor):
            continue
        clean_key = key[7:] if key.startswith("module.") else key
        state_dict[clean_key] = value
    if not state_dict:
        raise ValueError("No tensor parameters found in checkpoint")
    return state_dict


def load_checkpoint_strict(model: nn.Module, path: str, device: torch.device) -> None:
    checkpoint_path = Path(path)
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"PointNet checkpoint not found: {path}")

    # ``weights_only`` is unavailable in the PyTorch 1.8 environment used by
    # the original repository. Prefer it on newer versions, then fall back.
    try:
        checkpoint = torch.load(path, map_location=device, weights_only=True)
    except TypeError:
        checkpoint = torch.load(path, map_location=device)
    except Exception:
        checkpoint = torch.load(path, map_location=device, weights_only=False)

    state_dict = extract_state_dict(checkpoint)
    model.load_state_dict(state_dict, strict=True)


def parse_request(bottle) -> Tuple[int, float, int, np.ndarray]:
    if bottle is None or bottle.size() < 4:
        raise ValueError("Malformed request Bottle")

    request_id = int(bottle.get(0).asInt32())
    request_ts = float(bottle.get(1).asFloat64())
    camera = int(bottle.get(2).asInt32())
    payload = bottle.get(3).asList()
    if payload is None:
        raise ValueError("Request event payload is not a list")
    if payload.size() % 4 != 0:
        raise ValueError(f"Event payload length {payload.size()} is not divisible by 4")

    count = payload.size() // 4
    events = np.empty((count, 4), dtype=np.float64)
    for i in range(count):
        base = 4 * i
        events[i, 0] = payload.get(base).asInt32()
        events[i, 1] = payload.get(base + 1).asInt32()
        events[i, 2] = payload.get(base + 2).asFloat64()
        events[i, 3] = payload.get(base + 3).asInt32()
    return request_id, request_ts, camera, events


def write_reply(
    out_port,
    request_ts: float,
    request_id: int,
    status: str,
    xy: np.ndarray,
    conf: np.ndarray,
    diagnostics: Sequence[float],
    message: str = "",
) -> None:
    bottle = out_port.prepare()
    bottle.clear()
    bottle.addFloat64(float(request_ts))

    payload = bottle.addList()
    for i in range(NUM_JOINTS):
        payload.addFloat64(float(xy[i, 0]))
        payload.addFloat64(float(xy[i, 1]))
    for i in range(NUM_JOINTS):
        payload.addFloat64(float(conf[i]))

    bottle.addString(status)
    bottle.addInt32(int(request_id))
    stats = bottle.addList()
    for value in diagnostics:
        stats.addFloat64(float(value))
    bottle.addString(str(message))
    out_port.write()


def numpy_rasepc_reference(events: np.ndarray, channels: int, height: int, width: int) -> np.ndarray:
    """Independent NumPy reference used only by --self_test_rasepc."""
    work = np.asarray(events[:, :4], dtype=np.float64).copy()
    work[:, 2] -= work[:, 2].min()
    work[:, 2] = (work[:, 2] / work[:, 2].max()) / 1.001
    work[:, 2] *= channels

    t = work[:, 2]
    p = 2 * work[:, 3] - 1
    t0 = t.astype(np.int32)
    x = work[:, 0].astype(np.int32) - 1
    y = work[:, 1].astype(np.int32) - 1
    index = height * width * t0.astype(np.int64) + width * y.astype(np.int64) + x.astype(np.int64)

    total = channels * height * width
    polar = np.zeros(total, dtype=np.float32)
    time_acc = np.zeros(total, dtype=np.float32)
    count = np.zeros(total, dtype=np.float32)
    np.add.at(polar, index, p.astype(np.float32))
    np.add.at(time_acc, index, (t - t0).astype(np.float32))
    np.add.at(count, index, np.ones_like(x, dtype=np.float32))

    valid = count != 0
    flat_idx = np.nonzero(valid)[0]
    channel = (flat_idx // (height * width)).astype(np.float32)
    rem = flat_idx % (height * width)
    yy = (rem // width).astype(np.float32)
    xx = (rem % width).astype(np.float32)
    t_avg = time_acc[valid] / count[valid]
    t_avg = t_avg / channels + channel / channels
    return np.column_stack((channel, xx, yy, t_avg, polar[valid], count[valid])).astype(np.float32)


def _make_rasepc_test_events(seed: int = 17, count: int = 6000) -> np.ndarray:
    rng = np.random.RandomState(seed)
    # Match the repository input domain, including y=0 to exercise its exact
    # negative-flat-index behaviour after the internal ``-1``.
    return np.column_stack(
        (
            rng.randint(1, SENSOR_WIDTH + 1, size=count),
            rng.randint(0, SENSOR_HEIGHT, size=count),
            np.sort(rng.randint(0, 1000000, size=count)),
            rng.randint(0, 2, size=count),
        )
    ).astype(np.float64)


def _locate_upstream_rasterized(explicit_repo: str) -> Optional[Path]:
    candidates = []
    if explicit_repo:
        root = Path(explicit_repo).expanduser().resolve()
        candidates.extend((root / "dataset" / "rasterized.py", root / "rasterized.py"))

    script = Path(__file__).resolve()
    candidates.extend(
        (
            script.parent.parent / "dataset" / "rasterized.py",
            script.parent / "dataset" / "rasterized.py",
            Path.cwd() / "dataset" / "rasterized.py",
        )
    )

    for candidate in candidates:
        if candidate.is_file() and candidate.resolve() != script:
            return candidate
    return None


def _load_upstream_rasepc(path: Path):
    spec = importlib.util.spec_from_file_location("eventpointpose_upstream_rasterized", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load upstream RasEPC module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not hasattr(module, "RasEventCloud"):
        raise AttributeError(f"Upstream module has no RasEventCloud class: {path}")
    return module.RasEventCloud


def run_coordinate_self_test() -> None:
    # Reproduce both repository equations explicitly:
    #   EventPointPose preprocessing: X=(W-x_raw)+cam*W, y=H-y_raw,
    #   MeanLabel frame: [X-cam*W, H-y] = [W-x_raw, y_raw].
    #   hpe-core YARP export: [X-1-cam*W, y-1].
    raw_x = np.asarray([0, 1, 87, 214, SENSOR_WIDTH - 2, SENSOR_WIDTH - 1])
    raw_y = np.asarray([0, 1, 115, 136, SENSOR_HEIGHT - 2, SENSOR_HEIGHT - 1])
    timestamps = np.asarray([0.0, 0.001, 0.010, 0.025, 0.050, 0.100])
    polarity = np.asarray([0, 1, 0, 1, 1, 0])

    preprocessor = OnlineEventPreprocessor(
        input_preprocessing="already_filtered",
        background_domain="global",
        hotpixel_path="",
        width=SENSOR_WIDTH,
        height=SENSOR_HEIGHT,
        dt_us=70000.0,
    )

    for camera in (2, 3):
        x_global = (SENSOR_WIDTH - raw_x) + camera * SENSOR_WIDTH
        y_global = SENSOR_HEIGHT - raw_y
        meanlabel = np.column_stack(
            (x_global - camera * SENSOR_WIDTH, SENSOR_HEIGHT - y_global, timestamps, polarity)
        ).astype(np.float64)
        hpecore_log = np.column_stack(
            (x_global - 1 - camera * SENSOR_WIDTH, y_global - 1, timestamps, polarity)
        ).astype(np.float64)

        reconstructed, stats = preprocessor.process(hpecore_log, camera)
        if stats.accepted != hpecore_log.shape[0]:
            raise AssertionError(
                f"Coordinate test rejected valid events for camera {camera}: {stats}"
            )
        if not np.array_equal(reconstructed, meanlabel):
            raise AssertionError(
                f"hpe-core -> EventPointPose coordinate reconstruction mismatch for camera {camera}:\n"
                f"reconstructed={reconstructed}\nexpected={meanlabel}"
            )

    print(
        "Coordinate self-test passed: hpe-core local zero-based events reconstruct "
        "the original EventPointPose MeanLabel [x,y,t,p] representation for cameras 2 and 3."
    )


def run_rasepc_self_test(upstream_repo: str = "") -> None:
    events = _make_rasepc_test_events()
    implementation = RasEventCloud((RASEPC_CHANNELS, SENSOR_HEIGHT, SENSOR_WIDTH))
    torch_result = implementation.convert(events.copy()).numpy()
    numpy_result = numpy_rasepc_reference(
        events.copy(), RASEPC_CHANNELS, SENSOR_HEIGHT, SENSOR_WIDTH
    )

    if torch_result.shape != numpy_result.shape:
        raise AssertionError(
            f"RasEPC shape mismatch: torch={torch_result.shape}, numpy={numpy_result.shape}"
        )
    if not np.allclose(torch_result, numpy_result, rtol=0.0, atol=1e-7):
        max_error = float(np.max(np.abs(torch_result - numpy_result)))
        raise AssertionError(f"RasEPC numerical mismatch; max abs error={max_error}")

    upstream_path = _locate_upstream_rasterized(upstream_repo)
    if upstream_path is not None:
        upstream_class = _load_upstream_rasepc(upstream_path)
        upstream_result = upstream_class(
            (RASEPC_CHANNELS, SENSOR_HEIGHT, SENSOR_WIDTH)
        ).convert(events.copy()).numpy()
        if upstream_result.shape != torch_result.shape:
            raise AssertionError(
                f"Upstream RasEPC shape mismatch: upstream={upstream_result.shape}, "
                f"server={torch_result.shape}"
            )
        if not np.array_equal(upstream_result, torch_result):
            max_error = float(np.max(np.abs(upstream_result - torch_result)))
            raise AssertionError(
                f"Upstream RasEPC is not bitwise equal; max abs error={max_error}"
            )
        print(f"Upstream RasEPC comparison passed (bitwise equal): {upstream_path}")
    elif upstream_repo:
        raise FileNotFoundError(
            f"Could not find dataset/rasterized.py under --upstream_repo {upstream_repo}"
        )
    else:
        print(
            "Upstream dataset/rasterized.py was not found automatically; "
            "the independent NumPy differential test still passed."
        )

    print(
        f"RasEPC self-test passed: {events.shape[0]} events -> "
        f"{torch_result.shape[0]} points; max abs error <= 1e-7"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="EventPointPose PointNet YARP sidecar")
    parser.add_argument(
        "--model",
        default="/workspace/model_mounts/eventpointpose/PointNet/models/model.pth",
        help="Path to the PointNet MeanLabel checkpoint",
    )
    parser.add_argument("--event_port", default="/EventPointPose/events:i")
    parser.add_argument("--sklt_port", "--skeleton_port", dest="sklt_port", default="/EventPointPose/sklt:o")
    parser.add_argument("--device", default="cuda:0", help="cpu, cuda:N, or a GPU index")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--w", "--width", dest="w", type=int, default=SENSOR_WIDTH)
    parser.add_argument("--h", "--height", dest="h", type=int, default=SENSOR_HEIGHT)
    parser.add_argument("--fifo_size", type=int, default=FIFO_SIZE)
    parser.add_argument("--num_points", type=int, default=POINTNET_POINTS)
    parser.add_argument("--rasepc_channels", type=int, default=RASEPC_CHANNELS)
    parser.add_argument(
        "--input_preprocessing",
        "--input_mode",
        dest="input_preprocessing",
        choices=("already_filtered", "preprocessed", "raw"),
        default="already_filtered",
        help=(
            "already_filtered skips hot/background/IR filters; raw applies them. "
            "preprocessed is accepted as a legacy alias for already_filtered"
        ),
    )
    parser.add_argument(
        "--background_domain",
        "--background_scope",
        dest="background_domain",
        choices=("global", "local"),
        default="global",
        help="Only used with --input_preprocessing raw",
    )
    parser.add_argument("--background_dt_us", type=float, default=70000.0)
    parser.add_argument(
        "--hotpixel_path",
        default="",
        help=".npy/.csv/.png mask or directory; only used in raw mode",
    )
    parser.add_argument("--dump_debug_dir", "--dump_dir", dest="dump_debug_dir", default="")
    parser.add_argument("--dump_first_n", type=int, default=1)
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument(
        "--self_test_rasepc",
        action="store_true",
        help="Run an independent numerical RasEPC test and exit",
    )
    parser.add_argument(
        "--self_test_coordinates",
        action="store_true",
        help="Verify hpe-core data.log coordinates reconstruct MeanLabel coordinates",
    )
    parser.add_argument(
        "--self_test_all",
        action="store_true",
        help="Run coordinate and RasEPC validation without loading YARP/checkpoint",
    )
    parser.add_argument(
        "--upstream_repo",
        default="",
        help="Optional EventPointPose repo root for bitwise RasEPC comparison",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()

    ran_self_test = False
    if args.self_test_all or args.self_test_coordinates:
        run_coordinate_self_test()
        ran_self_test = True
    if args.self_test_all or args.self_test_rasepc:
        run_rasepc_self_test(args.upstream_repo)
        ran_self_test = True
    if ran_self_test:
        return 0

    # Backward-compatible alias used by an earlier draft of this sidecar.
    if args.input_preprocessing == "preprocessed":
        args.input_preprocessing = "already_filtered"

    if args.w != SENSOR_WIDTH or args.h != SENSOR_HEIGHT:
        raise SystemExit(
            f"The supplied MeanLabel checkpoint requires {SENSOR_WIDTH}x{SENSOR_HEIGHT}; "
            f"received {args.w}x{args.h}"
        )
    if args.fifo_size != FIFO_SIZE:
        raise SystemExit(f"This deployment requires fifo_size={FIFO_SIZE}")
    if args.num_points != POINTNET_POINTS:
        raise SystemExit(f"The supplied checkpoint requires num_points={POINTNET_POINTS}")
    if args.rasepc_channels != RASEPC_CHANNELS:
        raise SystemExit(f"EventPointPose RasEPC requires {RASEPC_CHANNELS} temporal channels")
    if args.input_preprocessing == "raw" and not args.hotpixel_path:
        raise SystemExit("--hotpixel_path is required with --input_preprocessing raw")
    if yarp is None:
        raise SystemExit("Could not import yarp. Enable the YARP Python bindings.")

    yarp.Network.init()
    if not yarp.Network.checkNetwork(2.0):
        raise SystemExit("YARP server is unavailable. Start yarpserver first.")

    engine = EventPointPoseEngine(args)

    in_port = yarp.BufferedPortBottle()
    out_port = yarp.BufferedPortBottle()
    if not in_port.open(args.event_port):
        raise SystemExit(f"Could not open event input port: {args.event_port}")
    if not out_port.open(args.sklt_port):
        in_port.close()
        raise SystemExit(f"Could not open skeleton output port: {args.sklt_port}")

    stop_requested = False

    def request_stop(_signum, _frame) -> None:
        nonlocal stop_requested
        stop_requested = True
        try:
            in_port.interrupt()
        except Exception:
            pass

    signal.signal(signal.SIGINT, request_stop)
    signal.signal(signal.SIGTERM, request_stop)

    print(
        "EventPointPose server ready: "
        f"device={engine.device}, input_preprocessing={args.input_preprocessing}, "
        f"background_domain={args.background_domain}, seed={args.seed}",
        flush=True,
    )

    try:
        while not stop_requested:
            request = in_port.read(True)
            if request is None:
                if stop_requested:
                    break
                continue

            request_id = -999
            request_ts = 0.0
            try:
                request_id, request_ts, camera, events = parse_request(request)
                if request_id < 0:
                    write_reply(
                        out_port,
                        request_ts,
                        request_id,
                        "SHUTDOWN",
                        np.zeros((NUM_JOINTS, 2), dtype=np.float32),
                        np.zeros(NUM_JOINTS, dtype=np.float32),
                        [0, len(engine.fifo), 0, 0.0],
                    )
                    break
                if camera not in (2, 3):
                    raise ValueError(
                        f"PointNet MeanLabel deployment supports DHP19 camera 2 or 3, got {camera}"
                    )

                status, xy, conf, diagnostics = engine.process_request(
                    request_id=request_id,
                    camera=camera,
                    events=events,
                )
                write_reply(
                    out_port,
                    request_ts,
                    request_id,
                    status,
                    xy,
                    conf,
                    diagnostics,
                )
                if args.verbose or status != "OK":
                    print(
                        "EventPointPose request "
                        f"id={request_id} ts={request_ts:.6f} camera={camera} "
                        f"input={events.shape[0]} accepted={int(diagnostics[0])} "
                        f"fifo={int(diagnostics[1])} rasepc={int(diagnostics[2])} "
                        f"status={status}",
                        flush=True,
                    )
            except Exception as exc:
                print(
                    f"EventPointPose request {request_id} failed: {type(exc).__name__}: {exc}",
                    file=sys.stderr,
                    flush=True,
                )
                write_reply(
                    out_port,
                    request_ts,
                    request_id,
                    "ERROR",
                    np.zeros((NUM_JOINTS, 2), dtype=np.float32),
                    np.zeros(NUM_JOINTS, dtype=np.float32),
                    [0, len(engine.fifo), 0, 0.0],
                    message=f"{type(exc).__name__}: {exc}",
                )
    finally:
        in_port.close()
        out_port.close()
        yarp.Network.fini()

    return 0


if __name__ == "__main__":
    sys.exit(main())
